version: '3.8'
services:
  main:
    restart: always
    env_file:
      - ./.env
    network_mode: host
    build:
      context: .
      target: develop-stage
      dockerfile: ./dockerfile
    volumes:
      - storage:/app/storage
volumes:
  storage: