version: '3.8'
services:
  main:
    restart: on-failure:5
    env_file:
      - ./.env
    network_mode: host
    build:
      context: .
      #target: build-stage
      dockerfile: ./dockerfile
    volumes:
      - storage:/app/storage
volumes:
  storage: